### ISSUE TITLE
replacement has length zero

### ISSUE THREAD

**Issue by shirleydaidai** [andreamrau/coseq#2]
Hi, 
I'm trying to run coseq using my raw count data. Here's an error msg I encountered:
```
> conds
 [1] 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0
[37] 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1
[73] 0 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 0 1 1 0 1 0 1
> runArcsin <- coseq(counts, K=2:40, norm="TMM", model="Normal",transformation="arcsin", parallel=T)
Running K = 2 ...
Running K = 3 ...
Running K = 4 ...
Running K = 5 ...
Running K = 6 ...
Running K = 7 ...
Running K = 8 ...
Running K = 9 ...
Running K = 10 ...
Running K = 11 ...
Running K = 12 ...
Running K = 13 ...
Running K = 14 ...
Running K = 15 ...
Running K = 16 ...
Running K = 17 ...
Running K = 18 ...
Running K = 19 ...
Running K = 20 ...
Running K = 21 ...
Running K = 22 ...
Running K = 23 ...
Running K = 24 ...
Running K = 25 ...
Running K = 26 ...
Running K = 27 ...
Running K = 28 ...
Running K = 29 ...
Running K = 30 ...
Running K = 31 ...
Running K = 32 ...
Running K = 33 ...
Running K = 34 ...
Running K = 35 ...
Running K = 36 ...
Running K = 37 ...
Running K = 38 ...
Running K = 39 ...
Running K = 40 ...
Error in all.results[match(Kmods, names(all.results))] <- tmp[which(unlist(lapply(tmp,  : 
  replacement has length zero

````

**Comment by andreamrau** [comment]
Hi, and thanks for reporting this issue --I definitely need to incorporate a more informative error message for this situation. This error means that for all models (K= 2, ..., 40) there was an error in estimating the associated Gaussian mixture model (and thus in the code when I start to organise the results in the `all.results list`, none of the models exists and the `replacement has length zero` message appears). The reason for this estimation error is likely linked to problems estimating the covariance matrices. 

A quick question about your example: since `conds` is a vector of length ~96 with two levels, your data represent two experimental conditions with ~48 samples in each? Since the Gaussian mixture model is trying to fit components with (96 x 96) covariance matrices of the most general form, that may be the problem. I would suggest trying to re-run the code using spherical (pk_Lk_Bk) or diagonal (pk_Lk_I) covariance matrices (see `?mixmodGaussianModel` in the Rmixmod package for more details about these forms of Gaussian mixture covariance matrices):

```
## Spherical Gaussian mixture model 
runArcsin_sph <- coseq(counts, K=2:40, norm="TMM", 
                              model="Normal",transformation="arcsin", 
                              parallel=T, GaussianModel="Gaussian_pk_Lk_Bk")

## Diagonal Gaussian mixture model
runArcsin_diag <- coseq(counts, K=2:40, norm="TMM", 
                              model="Normal",transformation="arcsin", 
                              parallel=T, GaussianModel="Gaussian_pk_Lk_I")
```

I would expect one or both of those possibilites to work in your case. Let me know!

**Comment by andreamrau** [comment]
I will try to incorporate an informative error message about this point very soon. Also, FYI I am in the process of making some changes to the package (specifically converting all the S3 methods and classes to S4), I hope to have it up soon.

**Comment by andreamrau** [comment]
The latest version of coseq now prints out an informative error message suggesting the use of alternative forms of Gaussian mixture model covaraince matrices in the case where all models have errors (following my reply above).
